server:
   port: 8081
spring:
  application:
    name: order

##数据库配置
  datasource:
    url: jdbc: mysql://192.168.43.181:3306/SpringCloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
##rabbitmq远程地址配置
  rabbitmq:
    host: 192.168.43.181
    port: 5672
    username: guest
    password: guest
  http:
    encoding:
      charset: utf-8
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8791/eureka/,http://peer2:8792/eureka/,http://peer3:8793/eureka/

  EVN:
      '我是你的大爷'hahah

#使用前缀进行配置
  girl:
    name: jack
    age: 15
